# Generated by Django 4.0.4 on 2022-05-07 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OP', 'On progress'), ('FN', 'Finished')], default='OP', max_length=2)),
                ('owner', models.ForeignKey(db_column='owner_qt_id', on_delete=django.db.models.deletion.CASCADE, related_name='owner_try', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_quiztry', to='quiz_app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_perf', to='quiz_app.answer')),
                ('owner', models.ForeignKey(db_column='owner_qp_id', on_delete=django.db.models.deletion.CASCADE, related_name='owner_perf', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_perf', to='quiz_app.question')),
                ('quiz_try', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_try_perf', to='quiz_action_app.quiztry')),
            ],
        ),
    ]
